name: recipes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  carousel_pro: ^1.0.0
  http: ^0.12.2
  get_it: ^5.0.3
  bloc: ^6.1.1
  flutter_bloc: ^6.1.1
  meta: ^1.2.4
  equatable: ^1.2.5
  formz: ^0.3.2
  flutter_secure_storage: ^3.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/

  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
